name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *" # Correct cron format for every 12 hours
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Jyotibrat
          outputs: dist/snake.svg?palette=github-dark # Default output directory

      - name: Move snake.svg to src directory
        run: mv dist/snake.svg src/snake.svg

      - name: Commit and push snake.svg
        run: |
          git config --global user.name 'Jyotibrat'
          git config --global user.email 'jyotibratb@gmail.com'
          git add src/snake.svg
          git commit -m "Update snake.svg"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
