name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history for correct branching

      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          user: Jyotibrat
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Calcutta
          config_display: regular
          plugin_languages: yes
          plugin_languages_limit: 5
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned

      - name: Move github-metrics.svg to src/Assets directory
        id: move
        run: |
          mkdir -p src/Assets  # Ensure directory exists
          mv metrics_renders/*.svg src/Assets/
        continue-on-error: true  # Continue even if no files to move

      - name: Commit and push github-metrics.svg
        if: success() && steps.move.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Jyotibrat'
          git config --global user.email 'jyotibratb@gmail.com'
          git add src/Assets/*.svg
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update github-metrics.svg"
            git push origin main
          fi
